/*
CREATE TABLE STUDENTS
(STUDENT_ID int,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
RELIGION VARCHAR(50),
GENDER VARCHAR(50),
AGE INT,
DOB DATE
)*/

/*
INSERT INTO STUDENTS VALUES
(01, 'RAM','KUMAR','HINDU','MALE',21,'2001-08-01'),
(02, 'SHYAM',NULL,'HINDU','GAY',20,'2000-07-12'),
(03,'NITIN','SINGH','HINDU','MALE',19,'2002-06-02'),
(NULL,'SUKESH','GANGWAR',NULL,'MALE',NULL,'2005-05-04'),
(04,NULL,NULL,'JAIN','FEMALE',16,'2007-06-09'),
(05,'FATIMA','ZAHARA','MUSLIM','FEMALE',20,'2003-01-19')
*/

/*
CREATE TABLE STUDENT_PERFORMANCE
(STUDENT_ID INT,
GRADE_ACADEMICS VARCHAR(10),
BEHAVIOUR VARCHAR(50),
EXTRA_CURRICULOR VARCHAR(50),
OVERALL_CGPA FLOAT
)

INSERT INTO STUDENT_PERFORMANCE VALUES
(01,'A','GOOD','FOOTBALL',8.5),
(02,'B','FAIR','CRICKET',8.0),
(NULL,NULL,'POOR',NULL,6.5),
(03,'B','VERY FAIR','GUITAR',7.5),
(04,'C','GOOD','CHESS',8.0),
(NULL,'A','GOOD','TABLE-TENNIS',8.7)
*/

/*
SELECT *
FROM STUDENTS

SELECT *
FROM STUDENT_PERFORMANCE
*/


/* USING GROUP BY AND ORDER BY*/

/*
SELECT RELIGION,COUNT(RELIGION) AS RELIGION_COUNT,GENDER,COUNT(GENDER),AGE,COUNT(AGE)
FROM STUDENTS
WHERE AGE>16
GROUP BY RELIGION,GENDER,AGE
*/

/*
SELECT FIRST_NAME,LAST_NAME,AGE
FROM STUDENTS
WHERE AGE>19
ORDER BY AGE DESC
*/

/*PERFORMING JOIN OPERATIONS ON BOTH THE TABLE*/

/*INNER JOIN ONLY CONSIST OF DATA THAT IS COMMON IN BOTH THE TABLE IT DOESNOT INCLUDE NULL VALUES*/
/*
SELECT *
FROM STUDENTS
INNER JOIN STUDENT_PERFORMANCE
ON STUDENTS.STUDENT_ID = STUDENT_PERFORMANCE.STUDENT_ID
*/


/*FULL OUTER JOIN CONSIST OF COMMON VALUES FROM BOTH THE TABLE + ALL THE OTHER VALUE INCLUDING NULL*/
/*
SELECT *
FROM STUDENTS
FULL OUTER JOIN STUDENT_PERFORMANCE
ON STUDENTS.STUDENT_ID=STUDENT_PERFORMANCE.STUDENT_ID
*/

/* LEFT OUTER JOIN RETURNS ALL THE VALUES FROM LEFT TABLE INCLUDING NULL VALUES + MATCHING VALUE FROM BOTH RIGHT AND LEFT TABLE*/
/*
SELECT * 
FROM STUDENTS
LEFT OUTER JOIN STUDENT_PERFORMANCE
ON STUDENTS.STUDENT_ID=STUDENT_PERFORMANCE.STUDENT_ID
*/

/*RIGHT OUTER JOIN RETURNS ALL VALUES FROM RIGHT TABLE INCLUDING NULL VALUES+MATCHING RECORDS FROM BOTH RIGHT AND LEFT TABLE*/
/*
SELECT STUDENTS.STUDENT_ID,FIRST_NAME,LAST_NAME,RELIGION,GRADE_ACADEMICS,OVERALL_CGPA,BEHAVIOUR
FROM STUDENTS
RIGHT OUTER JOIN STUDENT_PERFORMANCE
ON STUDENTS.STUDENT_ID=STUDENT_PERFORMANCE.STUDENT_ID
*/

